services:
  master:
    image: master:latest
    ports:
      - "8888:8888"
      - "8088:8088"
      - "8000:8000"
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../csc467data:/data
      
  worker:
    image: worker:latest
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../csc467data:/data
      
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  17.18.0.0/16
