services:
  base:
    build:
      context: ./docker/base
      tags:
        - "interactive_book:base"
    image: interactive_book:base
    
  bookshelves:
    build:
      context: ./docker/bookcase
      tags:
        - "bookcase:latest"
    init: true
    image: bookcase:latest
    ports:
      - "18888:8888"
      - "18088:8088"
      - "18000:8000"
      - "2222:22"
    volumes:
      - home:/home
      - ../bookcase:/bookcase # courses is a github repo containing lecture materials
    expose:
      - "22"
    hostname: bookcase
    container_name: bookcase
    networks:
      - compute
      
  compute:
    init: true
    image: interactive_book:base
    volumes:
      - home:/home
      - ../bookcase:/bookcase # courses is a github repo containing lecture materials
    expose:
      - "22"
    hostname: compute
    container_name: compute
    networks:
      - compute
    deploy:
      resources:
        limits:
          cpus: 2.0
      
networks:
  compute:
    name: compute
    driver: bridge

volumes:
  home:
